import sharp from 'sharp';
import { recognize } from 'tesseract.js';
import { env } from '../config/env';

export type Check = { status:string; score?:number; confidence:number; reason:string; [key:string]:unknown };
export async function inspect(path:string) { const image=sharp(path,{failOn:'error'}); const [metadata,stats]=await Promise.all([image.metadata(),image.stats()]); if(!metadata.width || !metadata.height || !metadata.format) throw new Error('Image has no readable dimensions or format'); return {metadata,stats}; }
/** Laplacian variance is a conventional sharpness signal; low values indicate few high-frequency edges. */
export async function laplacianBlur(path:string):Promise<Check> { const {data,info}=await sharp(path).resize({width:512,withoutEnlargement:true}).grayscale().raw().toBuffer({resolveWithObject:true}); if(info.width<3||info.height<3) return {status:'inconclusive',score:0,confidence:0,reason:'Image is too small for blur analysis.'}; const values:number[]=[]; for(let y=1;y<info.height-1;y++) for(let x=1;x<info.width-1;x++){const i=y*info.width+x;values.push(Math.abs(4*data[i]-data[i-1]-data[i+1]-data[i-info.width]-data[i+info.width]));} const mean=values.reduce((a,b)=>a+b,0)/values.length; const variance=values.reduce((a,b)=>a+(b-mean)**2,0)/values.length; const suspicious=variance<env.BLUR_THRESHOLD; return {status:suspicious?'suspicious':'pass',score:Number(variance.toFixed(2)),threshold:env.BLUR_THRESHOLD,confidence:Number(Math.min(.99,Math.abs(variance-env.BLUR_THRESHOLD)/Math.max(env.BLUR_THRESHOLD,1)+.5).toFixed(2)),reason:suspicious?'Low Laplacian variance may indicate blur; this is a heuristic.':'Laplacian variance is above the configured blur threshold.'}; }
export function blur(stats:sharp.Stats):Check { const variance=stats.channels.slice(0,3).reduce((sum,c)=>sum+c.stdev*c.stdev,0)/Math.min(3,stats.channels.length); const suspicious=variance<env.BLUR_THRESHOLD; return {status:suspicious?'suspicious':'pass',score:Number(variance.toFixed(2)),threshold:env.BLUR_THRESHOLD,confidence:Number(Math.min(.99,Math.abs(variance-env.BLUR_THRESHOLD)/Math.max(env.BLUR_THRESHOLD,1)+.5).toFixed(2)),reason:suspicious?'Low grayscale variance may indicate blur; this is a heuristic.':'Image detail variance is above the configured blur threshold.'}; }
export function brightness(stats:sharp.Stats):Check { const value=stats.channels.slice(0,3).reduce((sum,c)=>sum+c.mean,0)/Math.min(3,stats.channels.length); const status=value<env.LOW_BRIGHTNESS_THRESHOLD?'very_dark':value<env.LOW_BRIGHTNESS_THRESHOLD*1.35?'low_light':value>env.OVEREXPOSURE_THRESHOLD?'overexposed':'acceptable'; return {status,score:Number(value.toFixed(2)),confidence:status==='acceptable'?.72:.82,reason:status==='acceptable'?'Average brightness is within configured bounds.':`Average brightness suggests ${status}; lighting assessment is heuristic.`}; }
export function normalizeOcrText(value:string):string { return value.toUpperCase().replace(/[^A-Z0-9]/g,''); }
export async function ocr(path:string):Promise<Check> { try { const r=await recognize(path,'eng'); const raw=r.data.text.trim(); const normalized=normalizeOcrText(raw); return {status:'completed',rawText:raw,normalizedText:normalized,confidence:Number((r.data.confidence/100).toFixed(2)),reason:'OCR text can be inaccurate, particularly on small or obscured plates.'}; } catch { return {status:'unavailable',confidence:0,reason:'OCR could not complete; image processing continues.'}; } }
export function vehicle(text:string,confidence:number):Check { const valid=/^[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4}$/.test(text); return {status:valid?'format_valid':'format_unverified',text,formatValid:valid,confidence,reason:valid?'OCR output resembles the configured Indian registration format; this does not verify registration existence.':'OCR output does not resemble the configured registration format.'}; }
export function metadataCheck(m:sharp.Metadata):Check { const screenshotLike=[720,1080,1170,1284].includes(m.width??0)&&[1280,1920,2532,2778].includes(m.height??0); return {status:screenshotLike?'suspicious':'inconclusive',confidence:screenshotLike?.58:.35,reason:screenshotLike?'Dimensions resemble common screen captures; this is not forensic proof.':'No strong screenshot signal found; missing EXIF does not imply editing.',format:m.format,width:m.width,height:m.height,orientation:m.orientation,hasExif:Boolean(m.exif)}; }
